package com.malware.authservice.service;

import com.malware.authservice.data.dao.JpaUser;
import com.malware.authservice.data.domain.user.User;
import com.malware.authservice.data.dto.ProductDto;
import com.malware.authservice.data.repository.user.UserJpaRepository;
import com.malware.authservice.exception.CustomException;
import com.malware.authservice.external.ProductClient;
import com.malware.authservice.factory.IEntityMapper;
import io.github.resilience4j.retry.annotation.Retry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class UserService {

    private final ProductClient productClient;
    private final UserJpaRepository userJpaRepository;

    private final IEntityMapper<JpaUser, User> mapper;

    public User addUser(JpaUser jpaUser) {
        jpaUser.setUid(UUID.randomUUID().toString());
        return mapper.mapToModel(userJpaRepository.save(jpaUser));
    }

    public User getUser(String uid) throws CustomException {
        JpaUser user = userJpaRepository.findByUid(uid).orElseThrow(() -> new CustomException("User not found!"));
        return mapper.mapToModel(user);
    }

    public List<User> getAllUsers(Pageable pageable) {
        return userJpaRepository.findAll(pageable)
                .stream()
                .map(mapper::mapToModel)
                .collect(Collectors.toList());
    }

    @Retry(name = "productService", fallbackMethod = "fallback")
    public List<ProductDto> getUserProducts(String uid) {
        return productClient.getProducts(uid).getBody();
    }

    public List<ProductDto> fallback(String _message, Throwable throwable) {
        log.error("[FALLBACK] {}", throwable.getMessage());
        return new ArrayList<>();
    }
}
